name: apparel
description: AMOG, ILAS, TABAJONDA, TEJADA

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

  font_awesome_flutter: ^8.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true


  assets:
    - lib/assets/images/apparel2.png
    - lib/assets/images/apparel3.png
    - lib/assets/images/apparel4.png

  fonts:
    - family: Outfit
      fonts:
        - asset: lib/assets/fonts/Outfit-Thin.ttf
          weight: 100
        - asset: lib/assets/fonts/Outfit-ExtraLight.ttf
          weight: 200
        - asset: lib/assets/fonts/Outfit-Light.ttf
          weight: 300
        - asset: lib/assets/fonts/Outfit-Regular.ttf
          weight: 400
        - asset: lib/assets/fonts/Outfit-Medium.ttf
          weight: 500
        - asset: lib/assets/fonts/Outfit-SemiBold.ttf
          weight: 600
        - asset: lib/assets/fonts/Outfit-Bold.ttf
          weight: 700
        - asset: lib/assets/fonts/Outfit-ExtraBold.ttf
          weight: 800
        - asset: lib/assets/fonts/Outfit-Black.ttf
          weight: 900



